lex(mann,               [mann,_],n,sg,m,indef).
lex(mann,               [ehemann,_,_],n,sg,m,def).
lex(maenner,            [ehemann,_,_],n,pl,m,def).
lex(maenner,            [mann,_],n,pl,m,indef).
lex(frau,               [frau,_],n,sg,w,indef).
lex(frauen,             [frau,_],n,pl,w,indef).
lex(frau,               [ehefrau,_],n,sg,w,def). 
lex(frauen,             [ehefrau,_],n,pl,w,def).
lex(ehemann,            [ehemann,_,_],n,sg,m,def).
lex(ehemaenner,         [ehemann,_,_],n,pl,m,def).
lex(ehefrau,            [verheiratet,_,_],n,sg,w,def).
lex(eltern,             [eltern,_,_,_],n,pl,_,def).
lex(elternteil,         [elternteil,_,_],n,sg,_,indef).
lex(onkel,              [onkel,_,_],n,pl,m,def).
lex(onkel,              [onkel,_,_],n,sg,m,def).
lex(tante,              [tante,_,_],n,sg,w,def).
lex(tanten,             [tante,_,_],n,pl,w,def).
lex(cousin,             [cousin,_,_],n,sg,m,def).
lex(cousins,            [cousin,_,_],n,pl,w,def).
lex(neffe,              [neffe,_,_],n,sg,m,def).
lex(nichte,             [nichte,_,_],n,sg,w,def).
lex(vater,              [vater,_,_],n,sg,m,def).
lex(mutter,             [mutter,_,_],n,sg,w,def).
lex(bruder,             [bruder,_,_],n,sg,m,def).
lex(brueder,            [bruder,_,_],n,pl,m,def).
lex(schwester,          [schwester,_,_],n,sg,w,def).
lex(schwestern,         [schwester,_,_],n,pl,w,def).
lex(halbschwester,      [halbschwester,_,_],n,sg,w,def).
lex(halbschwestern,     [halbschwester,_,_],n,pl,w,def).
lex(halbbruder,         [halbbruder,_,_],n,sg,m,def).
lex(halbbrueder,        [halbbruder,_,_],n,pl,m,def).
lex(ehemann,            [ehemann,_],n,sg,m,indef).
lex(ehemaenner,         [ehemann,_],n,pl,m,indef).
lex(ehefrau,            [ehefrau,_],n,sg,w,indef).
lex(onkel,              [onkel,_],n,pl,m,indef).
lex(onkel,              [onkel,_],n,sg,m,indef).
lex(tante,              [tante,_],n,sg,w,indef).
lex(tanten,             [tante,_],n,pl,w,indef).
lex(cousin,             [cousin,_],n,sg,m,indef).
lex(cousins,            [cousin,_],n,pl,m,indef).
lex(cousine,             [cousine,_],n,sg,w,indef).
lex(cousinen,            [cousine,_],n,pl,w,indef).
lex(vater,              [vater,_],n,sg,m,indef).
lex(mutter,             [mutter,_],n,sg,w,indef).
lex(bruder,             [bruder,_],n,sg,m,indef).
lex(brueder,            [bruder,_],n,pl,m,indef).
lex(schwester,          [schwester,_],n,sg,w,indef).
lex(schwestern,         [schwester,_],n,pl,w,indef).
lex(halbschwester,      [halbschwester,_],n,sg,w,indef).
lex(halbschwestern,     [halbschwester,_],n,pl,w,indef).
lex(halbbruder,         [halbbruder,_],n,sg,w,indef).
lex(halbbrueder,        [halbbruder,_],n,pl,w,indef).
lex(verheiratet,        [verheiratet,_],adj,_,_,indef).
lex(verheiratet,        [verheiratet,_,_],adj,_,_,def).
lex(oma,                [oma, _, _],n,sg,w,def).
lex(opa,                [opa, _, _],n,sg,m,def).
lex(oma,                [oma, _],n,sg,w,indef).
lex(opa,                [opa, _],n,sg,m,indef).
lex(der,                der,artikel,sg,m,def).
lex(die,                die,artikel,sg,w,indef).
lex(die,                die,artikel,pl,_,def).
lex(dem,                dem,artikel,sg,m,def).
lex(ein,                ein,artikel,sg,m,indef).
lex(eine,               ein,artikel,sg,w,indef).
lex(von,                von,praeposition,_,_,pn).
lex(mit,                mit,praeposition,_,_,adj).
lex(ist,                ist,v,sg,_).
lex(sind,               ist,v,pl,_).
lex(wer,                frage,pronominaladverbien,_,_).
lex(ist,                frage,hilfsverben,sg,_).
lex(sind,               frage,hilfsverben,pl,_).
lex(und,                ',',konj,pl,_).
lex(oder,               ';',konj,pl,_).
